### ISSUE TITLE
Bot doesn't load

### ISSUE THREAD

**Issue by Mateocl05** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#169]
whwn I open run.bat it's only say 
C:\Users\***\OneDrive\Escritorio\PokeBall-SelfBot-Pokecord-Automation-master>py -3 launcher.py
and it doesn't do anything

**Comment by Hyperclaw79** [comment]
This is a duplicate of #158.
Please refer closed issues before opening a new one.
