### ISSUE TITLE
EventLoop is closed

### ISSUE THREAD

**Issue by KezGaming** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#171]
# Title: [Bug/Query/(leave empty)] ErrorName

# Body:

## Problem:
Here, write up a brief description about the error you are facing.

## Steps to Reproduce:
List out the steps you took to come upon the error.

## config.json:
Most of the problems arise due to badly edited config.json. Hence post the contents of it within codeblocks. (Select the contents here and press code button on top.)

## Traceback and Screenshots:
Paste the Traceback/Error here using codeblocks.
Post relevant screenshots.

## Specs.
**OS**:
**Bot Version**:
**Python Version**:

**Comment by Hyperclaw79** [comment]
It's impossible to debug from a single vague statement. Please provide the entire traceback along with relevant screenshots. Use the format provided, it's there for a reason.

**Comment by Hyperclaw79** [comment]
Closing this for now but feel free to reopen it with a valid response.
