### ISSUE TITLE
Setup.bat didn't run successfully

### ISSUE THREAD

**Issue by WildEmber1** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#172]
C:\Users\wilde\Desktop\PokeBall-SelfBot-Pokecord-Automation-master>py -3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokeball import PokeBall
  File "C:\Users\wilde\Desktop\PokeBall-SelfBot-Pokecord-Automation-master\pokeball.py", line 2, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

C:\Users\wilde\Desktop\PokeBall-SelfBot-Pokecord-Automation-master>timeout -1

Press any key to continue ...
Hey im trying to run the Self-Bot but when i press enter nothing happens and im not 100% sure on what the problem is but i think i know the problem just i dont know how to fix it can you please help?

**Comment by Hyperclaw79** [comment]
Looks like your setup.bat didn't finish successfully.   Rerun it after making sure Python is in path using `python --version`.

**Comment by Hyperclaw79** [comment]
Closing it till there are any further updates, since this a local issue.
