### ISSUE TITLE
Setup doesnt complete

### ISSUE THREAD

**Issue by OrangeHuskyEH** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#175]
# Title: [Bug/Query/(leave empty)] ErrorName

# Body: When u run setup , it runs in the command prompt and few files get downloaded and it closes itself after words , Idk how to setup Discord selfbots , i tried again but it didnt open after wards 
and It doesnt work in discord , i thought it setup on its own but doesnt work

Im wishing to learn more about script bots but i wanna start with Hyperclaw , so if you can help me set this scrpt up 

## Specs.
**OS**: windows 10
**Bot Version**: Idk , downloaded on 24th May 2020
**Python Version**: 3.8.0

**Comment by Hyperclaw79** [comment]
> Idk how to setup Discord selfbots
Start with, how to get the user `Token`s and various `ID`s like Message, Channel, Server, User, etc.

> i thought it setup on its own

You'll need to open the `run.bat` after finishing the setup. If files are getting downloaded, it means, your setup is most probably running well.

> but i wanna start with Hyperclaw

Err... you do realize that Hyperclaw is the author name and not the bot name right? 😅 

> Python Version: 3.8.0

Better to uninstall this and install 3.7.7 instead.

*P.S. The information you provided is not sufficient. Please mention your configs.json content and attach screenshots of your command prompts.*
`P.P.S Closing this as it seems to be a simple local issue - infact less of an issue but more of a missed step. Feel free to reopen if you have anything that needs to be further clarified.`

<kbd>The Premium Version comes with a video tutorial so if you're getting too confused and want some visual help along with my realtime support on Discord, consider purchasing it.</kbd>

**Comment by OrangeHuskyEH** [comment]
> Err... you do realize that Hyperclaw is the author name and not the bot name right? 😅

Didnt realise till now xD

> Better to uninstall this and install 3.7.7 instead.
mm ok 

> You'll need to open the run.bat after finishing the setup. If files are getting downloaded, it means, your setup is most probably running well.

There is no file named Run.bat in the folder when i extracted it , there is one named as Run , i thought that might be it but i have already run it and it doesnt make the bot work yet 
This is what it shows 
![image](https://user-images.githubusercontent.com/65847662/82777751-b34c4c80-9e6c-11ea-9d05-96009066bf43.png)
![image](https://user-images.githubusercontent.com/65847662/82777768-c232ff00-9e6c-11ea-8729-04bb401c35a9.png)

This is the folder and the files i got after i extracted the file 
![image](https://user-images.githubusercontent.com/65847662/82778187-446ff300-9e6e-11ea-8a43-54087223ea18.png)

**Comment by Hyperclaw79** [comment]
> There is no file named Run.bat in the folder when i extracted it , there is one named as Run

It's the same file. `.bat` is an extension and you probably don't have extension display enabled in your folder options.

> This is what it shows

It says that your token is invalid. Post your token which you pasted, censoring a few letters in between.
Also, specify how you got the token and whether you have 2 factor authentication enabled.

**Comment by OrangeHuskyEH** [comment]
> It's the same file. .bat is an extension and you probably don't have extension display enabled in your folder options.

oh ok

>It says that your token is invalid. Post your token which you pasted, censoring a few letters in between.
Also, specify how you got the token and whether you have 2 factor authentication enabled.

No i dont have 2 factor authentication enabled , and i didnt paste the Token ID , it didnt ask me to , but when i try to paste it , the CMD Prompt auto closes

**Comment by Hyperclaw79** [comment]
> No i dont have 2 factor authentication enabled , and i didnt paste the Token ID , it didnt ask me to , but when i try to paste it , the CMD Prompt auto closes

You're supposed to edit your config file and put the token there. The script itself won't ask you anything. You can fine tune the configs to your liking.
