### ISSUE TITLE
Auto Catcher is not Working for me

### ISSUE THREAD

**Issue by ObliviousDonkey** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#188]
Pokecord did something to the images.
The hashes doesn't work for me anymore :(

**Comment by Hyperclaw79** [comment]
Which version of the selfbot are you using?
The only working one is the Premium Version's V6.1.2

**Comment by ObliviousDonkey** [comment]
> Which version of the selfbot are you using?
> The only working one is the Premium Version's V6.1.2

It was working fine yesterday. But It couldn't identify any pokémon today. I hashed the images of the pokemons spawned today, and compared the result with the hash of  yesterday's pokemons. Damn the result is different for every pokemons! Eg. Yesterday axew's hash was f3e3c383878381e3. And today, Axew's hash was f1f1f0e1f18181f3

**Comment by Hyperclaw79** [comment]
I can't really help you out without the version number.

**Comment by ObliviousDonkey** [comment]
It's v6.1.2. I think the hashes got deleted in the auto catcher folder. Not sure tho

**Comment by Hyperclaw79** [comment]
The updated version is now v6.1.3 and takes care of any missing keyerrors.

P.S. As mentioned earlier, you can contact me on Discord for Premium
Versions related issues/queries.
