### ISSUE TITLE
Something went wrong when I tried to run "run.bat

### ISSUE THREAD

**Issue by masontree** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#193]
I got this whenever I tried to  use run.bat
I have no clue what to do pls help
![Annotation 2020-08-09 231840](https://user-images.githubusercontent.com/69446560/89751702-d7482300-da96-11ea-920f-71224875ada9.png)

**Comment by Hyperclaw79** [comment]
Refer to #161 to add Python to path.
After that, edit both your `setup.bat` and `run.bat` with notepad and replace the `py -3` with `python`.

**Comment by Hyperclaw79** [comment]
Closing this as a stale issue with the assumption of the problem being solved. Feel free to reopen it otherwise.

**Comment by ofui** [comment]
it didnt work for me it still says press key to continue then closes

**Comment by Hyperclaw79** [comment]
@ofui Cannot help without any screenshots. But my guess is that it's a python path issue. Check the output for `where python`. If the first location points to windows apps, then force delete that.

**Comment by Vaibhboy2** [comment]
hey hyperclaw79 can u please make a video and send here in how to setup

**Comment by Hyperclaw79** [comment]
@Vaibhboy2 That's already a tutorial video available for the Premium Version. The public version here is 3yrs+ old code which doesn't work anymore.
