### ISSUE TITLE
Unable to run setup.bat

### ISSUE THREAD

**Issue by arun-singh-as** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#198]
# Title: Query

# Body:  error in setup.bait

## Problem:
I am not getting any option to  run setup.bait and run.bat
i dont know where to run then as when i use atom it didnt get any run option.

## Traceback and Screenshots:
![image](https://user-images.githubusercontent.com/72333282/95010372-74ae7600-0646-11eb-9baa-434348602345.png)
![image](https://user-images.githubusercontent.com/72333282/95010379-8f80ea80-0646-11eb-8745-b40396ed06b0.png)
![image](https://user-images.githubusercontent.com/72333282/95010388-9f003380-0646-11eb-8029-6a5234d7e0bd.png)

## Specs.
**OS**:window 10
**Bot Version**:latest
**Python Version**:3.8

**Comment by Hyperclaw79** [comment]
I am not able to make any sense from those screenshots. Why are there two instances of setup.bat and run.bat?

What happens when you double click it? Looks like your Atom IDE is messing with the files. You'll have to google how to disable opening batch files with Atom.

**Comment by Hyperclaw79** [comment]
Closing it due to inactivity. Feel free to reopen it if the problem persists.
