### ISSUE TITLE
Requires Windows C++ build tools eror

### ISSUE THREAD

**Issue by PandaDaBot6** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#199]
# Title: 

# Body:

## Problem:
It says you need 14.0+ Windows C++ build tools
## Steps to Reproduce:
List out the steps you took to come upon the error.

## config.json:
{
   "token": "empty for here",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": false,
   "priority_only": false
}

## Traceback and Screenshots:
![image](https://user-images.githubusercontent.com/61565838/96377581-16a48700-114c-11eb-8141-c308ab9a5bd7.png)

## Specs.
**OS**:
**Bot Version**:
**Python Version**:

**Comment by Hyperclaw79** [comment]
Install Visual C++ 2015 Redistribution from [here](https://www.microsoft.com/en-gb/download/details.aspx?id=48145).
Then restart your system and that should fix it.
