### ISSUE TITLE
Poketwo compatibility

### ISSUE THREAD

**Issue by xch25** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#200]
Is the bot still functional for Poketwo bit after they added background and dynamic changes to images?

**Comment by Hyperclaw79** [comment]
Currently and mostly forever, the only working Selfbot against Poketwo!
#201

**Comment by xch25** [comment]
Woa really?? I am interested in buying it. How does it work? Is there any tutorial? I don’t know know anything about programming if that’s necessary to run it😕
Has the bot a feature to whitelist some pokes?

Xavier Costa Hoyo

El 30 oct 2020, a las 13:48, Harshith Thota <notifications@github.com> escribió:

﻿

Currently and mostly forever, the only working Selfbot against Poketwo!
#201<https://github.com/Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation/pull/201>

**Comment by Hyperclaw79** [comment]
> Is there any tutorial?
Video Tutorial + Text Instructions + Discord Support

> I don’t know know anything about programming
None required!

> Has the bot a feature to whitelist some pokes?
You can whitelist pokemons, servers and channels and heck lot more of customization.

**Comment by HOPE-NEXUS** [comment]
> Currently and mostly forever, the only working Selfbot against Poketwo!
> #201

Not *only *

**Comment by Hyperclaw79** [comment]
> Not *only *
*the only non-ripoff, non-scammy, non-amaeturish working selfbot against poketwo.

P.S. A word of advice - if you're trying to use other people's repos to advertise your scams, at least change the readme lmao

**Comment by HOPE-NEXUS** [comment]
> > Not *only *
> 
> *the only non-ripoff, non-scammy, non-amaeturish working selfbot against poketwo.
> 
> P.S. A word of advice - if you're trying to use other people's repos to advertise your scams, at least change the readme lmao

Why would I advertise in your Issue section.Also,if you think for 1-2people I might be doing this then lol, why would I when I do have Hundreds?

Btw I won't jump which selfbot is better but rather than that I would appreciate your as well as mine hard work?
FYI:- NOT A SCAM , NOT A AMATEUR.
You bot is in PYTHON, MINE IS IN NODE.JS.

Also,what did you mean by updating the Readme?
